/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type MarketItemStruct = {
  itemId: BigNumberish;
  nftContract: string;
  tokenId: BigNumberish;
  creator: string;
  seller: string;
  owner: string;
  price: BigNumberish;
  sold: boolean;
};

export type MarketItemStructOutput = [
  BigNumber,
  string,
  BigNumber,
  string,
  string,
  string,
  BigNumber,
  boolean
] & {
  itemId: BigNumber;
  nftContract: string;
  tokenId: BigNumber;
  creator: string;
  seller: string;
  owner: string;
  price: BigNumber;
  sold: boolean;
};

export interface MarketInterface extends utils.Interface {
  functions: {
    "createMarketItem(address,uint256,uint256)": FunctionFragment;
    "createMarketSale(address,uint256)": FunctionFragment;
    "fetchAuthorsCreations(address)": FunctionFragment;
    "fetchMarketItems()": FunctionFragment;
    "fetchMyNFTs()": FunctionFragment;
    "fetchSingleItem(uint256)": FunctionFragment;
    "getListingPrice()": FunctionFragment;
    "putItemToResell(address,uint256,uint256)": FunctionFragment;
    "updateMarketItemPrice(uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createMarketItem",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarketSale",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fetchAuthorsCreations",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "fetchMarketItems",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fetchMyNFTs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fetchSingleItem",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getListingPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "putItemToResell",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMarketItemPrice",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createMarketItem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarketSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchAuthorsCreations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchMarketItems",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchMyNFTs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchSingleItem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getListingPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "putItemToResell",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMarketItemPrice",
    data: BytesLike
  ): Result;

  events: {
    "MarketItemCreated(uint256,address,uint256,address,address,address,uint256)": EventFragment;
    "MarketItemDeleted(uint256)": EventFragment;
    "ProductListed(uint256)": EventFragment;
    "ProductSold(uint256,address,uint256,address,address,address,uint256)": EventFragment;
    "ProductUpdated(uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "MarketItemCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MarketItemDeleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProductListed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProductSold"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProductUpdated"): EventFragment;
}

export type MarketItemCreatedEvent = TypedEvent<
  [BigNumber, string, BigNumber, string, string, string, BigNumber],
  {
    itemId: BigNumber;
    nftContract: string;
    tokenId: BigNumber;
    creator: string;
    seller: string;
    owner: string;
    price: BigNumber;
  }
>;

export type MarketItemCreatedEventFilter =
  TypedEventFilter<MarketItemCreatedEvent>;

export type MarketItemDeletedEvent = TypedEvent<
  [BigNumber],
  { itemId: BigNumber }
>;

export type MarketItemDeletedEventFilter =
  TypedEventFilter<MarketItemDeletedEvent>;

export type ProductListedEvent = TypedEvent<[BigNumber], { itemId: BigNumber }>;

export type ProductListedEventFilter = TypedEventFilter<ProductListedEvent>;

export type ProductSoldEvent = TypedEvent<
  [BigNumber, string, BigNumber, string, string, string, BigNumber],
  {
    itemId: BigNumber;
    nftContract: string;
    tokenId: BigNumber;
    creator: string;
    seller: string;
    owner: string;
    price: BigNumber;
  }
>;

export type ProductSoldEventFilter = TypedEventFilter<ProductSoldEvent>;

export type ProductUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  { itemId: BigNumber; oldPrice: BigNumber; newPrice: BigNumber }
>;

export type ProductUpdatedEventFilter = TypedEventFilter<ProductUpdatedEvent>;

export interface Market extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MarketInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createMarketItem(
      nftContract: string,
      tokenId: BigNumberish,
      price: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createMarketSale(
      nftContract: string,
      itemId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    fetchAuthorsCreations(
      author: string,
      overrides?: CallOverrides
    ): Promise<[MarketItemStructOutput[]]>;

    fetchMarketItems(
      overrides?: CallOverrides
    ): Promise<[MarketItemStructOutput[]]>;

    fetchMyNFTs(overrides?: CallOverrides): Promise<[MarketItemStructOutput[]]>;

    fetchSingleItem(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[MarketItemStructOutput]>;

    getListingPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    putItemToResell(
      nftContract: string,
      itemId: BigNumberish,
      newPrice: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateMarketItemPrice(
      id: BigNumberish,
      newPrice: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  createMarketItem(
    nftContract: string,
    tokenId: BigNumberish,
    price: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createMarketSale(
    nftContract: string,
    itemId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  fetchAuthorsCreations(
    author: string,
    overrides?: CallOverrides
  ): Promise<MarketItemStructOutput[]>;

  fetchMarketItems(
    overrides?: CallOverrides
  ): Promise<MarketItemStructOutput[]>;

  fetchMyNFTs(overrides?: CallOverrides): Promise<MarketItemStructOutput[]>;

  fetchSingleItem(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<MarketItemStructOutput>;

  getListingPrice(overrides?: CallOverrides): Promise<BigNumber>;

  putItemToResell(
    nftContract: string,
    itemId: BigNumberish,
    newPrice: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateMarketItemPrice(
    id: BigNumberish,
    newPrice: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createMarketItem(
      nftContract: string,
      tokenId: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createMarketSale(
      nftContract: string,
      itemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    fetchAuthorsCreations(
      author: string,
      overrides?: CallOverrides
    ): Promise<MarketItemStructOutput[]>;

    fetchMarketItems(
      overrides?: CallOverrides
    ): Promise<MarketItemStructOutput[]>;

    fetchMyNFTs(overrides?: CallOverrides): Promise<MarketItemStructOutput[]>;

    fetchSingleItem(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<MarketItemStructOutput>;

    getListingPrice(overrides?: CallOverrides): Promise<BigNumber>;

    putItemToResell(
      nftContract: string,
      itemId: BigNumberish,
      newPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateMarketItemPrice(
      id: BigNumberish,
      newPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "MarketItemCreated(uint256,address,uint256,address,address,address,uint256)"(
      itemId?: BigNumberish | null,
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      creator?: null,
      seller?: null,
      owner?: null,
      price?: null
    ): MarketItemCreatedEventFilter;
    MarketItemCreated(
      itemId?: BigNumberish | null,
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      creator?: null,
      seller?: null,
      owner?: null,
      price?: null
    ): MarketItemCreatedEventFilter;

    "MarketItemDeleted(uint256)"(itemId?: null): MarketItemDeletedEventFilter;
    MarketItemDeleted(itemId?: null): MarketItemDeletedEventFilter;

    "ProductListed(uint256)"(
      itemId?: BigNumberish | null
    ): ProductListedEventFilter;
    ProductListed(itemId?: BigNumberish | null): ProductListedEventFilter;

    "ProductSold(uint256,address,uint256,address,address,address,uint256)"(
      itemId?: BigNumberish | null,
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      creator?: null,
      seller?: null,
      owner?: null,
      price?: null
    ): ProductSoldEventFilter;
    ProductSold(
      itemId?: BigNumberish | null,
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      creator?: null,
      seller?: null,
      owner?: null,
      price?: null
    ): ProductSoldEventFilter;

    "ProductUpdated(uint256,uint256,uint256)"(
      itemId?: BigNumberish | null,
      oldPrice?: BigNumberish | null,
      newPrice?: BigNumberish | null
    ): ProductUpdatedEventFilter;
    ProductUpdated(
      itemId?: BigNumberish | null,
      oldPrice?: BigNumberish | null,
      newPrice?: BigNumberish | null
    ): ProductUpdatedEventFilter;
  };

  estimateGas: {
    createMarketItem(
      nftContract: string,
      tokenId: BigNumberish,
      price: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createMarketSale(
      nftContract: string,
      itemId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    fetchAuthorsCreations(
      author: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fetchMarketItems(overrides?: CallOverrides): Promise<BigNumber>;

    fetchMyNFTs(overrides?: CallOverrides): Promise<BigNumber>;

    fetchSingleItem(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getListingPrice(overrides?: CallOverrides): Promise<BigNumber>;

    putItemToResell(
      nftContract: string,
      itemId: BigNumberish,
      newPrice: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateMarketItemPrice(
      id: BigNumberish,
      newPrice: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createMarketItem(
      nftContract: string,
      tokenId: BigNumberish,
      price: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createMarketSale(
      nftContract: string,
      itemId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    fetchAuthorsCreations(
      author: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fetchMarketItems(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fetchMyNFTs(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fetchSingleItem(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getListingPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    putItemToResell(
      nftContract: string,
      itemId: BigNumberish,
      newPrice: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateMarketItemPrice(
      id: BigNumberish,
      newPrice: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
